### ISSUE TITLE
ツイート表示管理にホットキーによる一時停止を加える

### ISSUE THREAD

**Issue by pasta04** [RTAinJapan/rtainjapan-layouts#507]
ツイートが多すぎると高速で流れていくため、表示したいツイートを見かけても操作が間に合わないことがある。
スクロール操作で停止することは可能だが、マウス操作よりもキーボードで止められる方が反応が早くてよい。

Twitchのモデレータービューにおけるチャット一時停止がAltなので、NodeCGでもAltで止められるようにする。

**Comment by pasta04** [comment]
TwitterのAPIを実装してからやる

**Comment by Hoishin** [comment]
もはやAPIから流れてくることがない
