### ISSUE TITLE
5人以上の走者がいる場合のdashboard修正

### ISSUE THREAD

**Issue by cma2819** [RTAinJapan/rtainjapan-layouts#641]
5人以上の走者がいるゲームで、以下のような状況になった

- 5人目以降の走者情報を編集できない（削除もできない）
- dashboard から存在が確認できず、タイマー操作もできないため、個人タイマー全てを止めたつもりでもマスタータイマーが止まらない（5人目以降のタイマーが生きているため）

dashboard で5人目以降を表示する（少なくとも編集はできるようにする）ことで、5人目以降が見えない状況を修正する

**Comment by pasta04** [comment]
[↑] [↓]ボタンで走者情報を入れ替えられるようになると、リレーとか企画系で情報を入れ替えるのが簡単になる。これの対応のついでに入れられると、オペレーション上、結構うれしいと思われる。

**Comment by Hoishin** [comment]
- current/next runに入るとき4人までで上限、5人以上はカット
- scheduleから5人以上の走者一覧を持ってこれるので、プルダウンか何かで簡単に走者を入れ替えられるUIにする

**Comment by cma2819** [comment]
多分ついでにSPECIALのダッシュボードもなおす

**Comment by pasta04** [comment]
- Editの各行に走者情報入れ替えのボタンを用意。
- ボタンはMenu+MenuItemで、クリックするとそのゲームの走者一覧が出る
- 走者名をクリックするとその行が入れ替わる
- 他の行との入れ替えみたいなのは要らない
