### ISSUE TITLE
ゲーム情報と解説応募の紐づけ方法改善

### ISSUE THREAD

**Issue by pasta04** [RTAinJapan/rtainjapan-layouts#644]
# 概要
- https://github.com/RTAinJapan/rtainjapan-layouts/blob/master/src/extension/tracker.ts#L124-L138
  - ![image](https://user-images.githubusercontent.com/3125070/210839034-431e578e-aee7-4475-9567-8308859f98e1.png)
- Trackerのゲーム情報と解説情報の紐づけは、ゲーム名が一致するかどうかで見ている。
- スケジュールのゲーム名は走者要望とかなんやかんやでコロコロ変わるため、一致しないとNodeCGに解説者名が出てこないということになる

# やりたいこと
- スケジュール名がコロコロ変わっても解説者がちゃんと表示されるようにしたい
- 解説応募のシートにはOengusのcategoryIdが記載してあるため、TrackerのDescriptionあたりにこのcategoryIdを入れることで完璧にマッチするようにする

**Comment by Hoishin** [comment]
~~trackerのtech notesにJSONを書くのはどうかという話をした~~

**Comment by pasta04** [comment]
Descriptionだと一般ユーザーでも見れるのでイマイチだった

**Comment by Hoishin** [comment]
- NodeCGでバックアップっぽいゲームをスケジュールとして入れない
- trackerにはまっさきにバックアップ含めて入れる
- trackerのpkを使って解説の登録をするようにする
- NodeCGで解説を取得する時は、trackerのpkをつかう
