### ISSUE TITLE
走者カメラのデフォルト値をオンにする

### ISSUE THREAD

**Issue by cma2819** [RTAinJapan/rtainjapan-layouts#653]
オフライン走者の場合、毎回カメラ有に設定するオペレーションが手間なので、そこを省略したい。

configBundleに `onsite` なフラグがあったはずなので、それを使えばよさそう。

**Comment by pasta04** [comment]
初期値はtrackerからデータを取得するところで入れている。
ここにisOnsiteのフラグを見て値を変化させる処理を加える
https://github.com/RTAinJapan/rtainjapan-layouts/blob/master/src/extension/tracker.ts#L121

**Comment by cma2819** [comment]
オンラインでもカメラ有の割合も多いことや、カメラOFF表示に気づかずに進めてしまうことも多いので、常にデフォルトONにする。
