### ISSUE TITLE
バックアップの run を schedule に追加しないようにする

### ISSUE THREAD

**Issue by cma2819** [RTAinJapan/rtainjapan-layouts#654]
tracker から取得できる speedruns には、スケジュールに乗っていない（order = null）な run も含まれる。

現状 `order` をチェックせずに schedule に追加しているため、バックアップのランもセットアップ画面に出てきたりしてしまう。

`order != null`  なランのみ schedule に乗せるよう、 filter 等で対応する。

**Comment by pasta04** [comment]
マージ完了
