### ISSUE TITLE
寄付有無を設定可能にする

### ISSUE THREAD

**Issue by cma2819** [RTAinJapan/rtainjapan-layouts#664]
ex イベントでは寄付がないため、寄付の有無を bundleConfig で設定できるようにしたい。

- bundleConfig には boolean で保持しておけばよい
- Omnibar 上で寄付に関する情報は表示しないようにする

**Comment by pasta04** [comment]
trackerのwebsocketはoptionalにする。
設定が無かったら繋がない

**Comment by pasta04** [comment]
> trackerのwebsocketはoptionalにする。 設定が無かったら繋がない

https://github.com/RTAinJapan/rtainjapan-layouts/pull/676 で対応
