### ISSUE TITLE
タイマーが動いているときは次のゲームのチェックリストを表示する

### ISSUE THREAD

**Issue by cma2819** [RTAinJapan/rtainjapan-layouts#683]
2レーン構成のとき、RTA進行中にセットアップを進めるとチェックリストを入力できない。

RTA終了後にチェックリストを入力することになり、形骸化しそう。

内部では各スケジュール毎にチェックリストの完了状況を保持しておき、ゲームを戻したりしても状態が保持されているのがよさそう。ミスったときにチェック外すのが面倒なので、全てチェックを外すボタンもあってもよさそうかも？

見た目上タイマースタートと同時にチェックリストが全解除されたようにみえるので、チェックリスト上とかに「どのゲームのセットアップ状況か」を書いておいてわかるようにしたほうがよい。

**Comment by pasta04** [comment]
現状以下だけど、

```js
{
  name: stringl
  complete: boolean
}[]
```

こんな感じの構造になるか

```js
{
  pk: number; // runのpkと対応
  checklist: {
    name: stringl
    complete: boolean
  }[]
}[]
```

**Comment by cma2819** [comment]
こんな感じでやろうとしていた

```typescript
// checklist.d.ts
{
  pk: string;
  name: string;
}
```

```ts
// run.d.ts
{
   // ...略
  checkStatus: {
    pk: string;
    complete: boolean;
  }[]
```

**Comment by pasta04** [comment]
- もとのchecklistはpkと表示文字列の定義だけを担当する。dashboard等からこのreplicantの更新は行われなくなる。
- pkとしてUUIDを払い出す。
- nameが同じならUUIDを変えないようにする
- NodeCG再起動して、チェック済みの項目がリセットされちゃった！なんてことは起こらないようにいい感じにする
