### ISSUE TITLE
一部レイアウトでFitTextがフォントサイズを0にしてしまう

### ISSUE THREAD

**Issue by yagamuu** [RTAinJapan/rtainjapan-layouts#689]
以下対応後、縦にゲームタイトル/カテゴリを並べるタイプのGameInfoで、高さが不定な為無限にFitTextが作動してしまい、最終的にフォントサイズが0になってしまう。
https://github.com/RTAinJapan/rtainjapan-layouts/pull/685
![image](https://user-images.githubusercontent.com/13300790/235277932-0422d695-fbd4-4329-867f-bfa3cda982a1.png)
CSSを適切に設定し不要なFitTextを行わないように修正する。

**Comment by yagamuu** [comment]
やり方正しいかわかりませんが、以下を`placeItems: "stretch"`にすれば治るのを確認
https://github.com/RTAinJapan/rtainjapan-layouts/blob/master/src/browser/graphics/components/game-info/semi-horizontal.tsx#L35
https://github.com/RTAinJapan/rtainjapan-layouts/blob/master/src/browser/graphics/components/game-info/vertical.tsx#L37

**Comment by Hoishin** [comment]
そもそもの原因が、widthとheightで同じsetSizeしてるからのはず

**Comment by pasta04** [comment]
https://github.com/RTAinJapan/rtainjapan-layouts/commit/c6a6b99b657f51100f1b634d5dc574522785fc77 で暫定対応は済

**Comment by Hoishin** [comment]
9d9b47f34dfe17ae718c93fef267f0cde57e4cd7 でなおった
