### ISSUE TITLE
[RiJW2023] 新規レイアウトの作成

### ISSUE THREAD

**Issue by cma2819** [RTAinJapan/rtainjapan-layouts#730]
> - document/main/layout+_3x4_1.png
> - document/main/layout+_FFCC.png

**Comment by pasta04** [comment]
いずれもレイアウトファイルとしては似たようなのをコピーして名前変えるだけでよい。
ゲーム画面はOBS側で位置調整。

# 3x4_1
4:3ソロ、10:9ソロなどに代表されるL型480 ( `TemplateL480` ) と同様で、ゲーム画面の位置が違うだけ。

# FFCC
4:3 2人レースに代表されるヨコ型260 ( `TemplateH260` ) と同様で、ゲーム画面の位置が違うだけ。
特殊レイアウトであるため、明にコミットせず、OBSのシーン登録でヨコ型260のどれかを使ってもいいと思う。
