### ISSUE TITLE
5人以上走者がいる場合にマスタータイマーが止まらない

### ISSUE THREAD

**Issue by yagamuu** [RTAinJapan/rtainjapan-layouts#738]
#714 にてダッシュボードの修正が行われたが、依然として5人目以降の個人タイマーを止めることができないためマスタータイマーを止めることができない。
ダッシュボード内にタイマーを有効とするチェックボックスを用意するなどでマスタータイマーを止めれるように改修する。

**Comment by pasta04** [comment]
https://github.com/RTAinJapan/rtainjapan-layouts/pull/741 の対応で修正完了
